Parallel: 45. Serial: 0
test_case01_mutate_list_ahead_of_ctx (numba.tests.test_withlifting.TestLiftObj.test_case01_mutate_list_ahead_of_ctx) ... ok
test_case02_mutate_array_ahead_of_ctx (numba.tests.test_withlifting.TestLiftObj.test_case02_mutate_array_ahead_of_ctx) ... ok
test_case03_create_and_mutate (numba.tests.test_withlifting.TestLiftObj.test_case03_create_and_mutate) ... ok
test_case04_bogus_variable_type_info (numba.tests.test_withlifting.TestLiftObj.test_case04_bogus_variable_type_info) ... ok
test_case05_bogus_type_info (numba.tests.test_withlifting.TestLiftObj.test_case05_bogus_type_info) ... ok
test_case06_double_objmode (numba.tests.test_withlifting.TestLiftObj.test_case06_double_objmode) ... ERROR
test_case07_mystery_key_error (numba.tests.test_withlifting.TestLiftObj.test_case07_mystery_key_error) ... ok
test_case08_raise_from_external (numba.tests.test_withlifting.TestLiftObj.test_case08_raise_from_external) ... ok
test_case09_explicit_raise (numba.tests.test_withlifting.TestLiftObj.test_case09_explicit_raise) ... ok
test_case10_mutate_across_contexts (numba.tests.test_withlifting.TestLiftObj.test_case10_mutate_across_contexts) ... ok
test_case10_mutate_array_across_contexts (numba.tests.test_withlifting.TestLiftObj.test_case10_mutate_array_across_contexts) ... ok
test_case11_define_function_in_context (numba.tests.test_withlifting.TestLiftObj.test_case11_define_function_in_context) ... ok
test_case12_njit_inside_a_objmode_ctx (numba.tests.test_withlifting.TestLiftObj.test_case12_njit_inside_a_objmode_ctx) ... ok
test_case14_return_direct_from_objmode_ctx (numba.tests.test_withlifting.TestLiftObj.test_case14_return_direct_from_objmode_ctx) ... ok
test_case15_close_over_objmode_ctx (numba.tests.test_withlifting.TestLiftObj.test_case15_close_over_objmode_ctx) ... expected failure
test_case16_scipy_call_in_objmode_ctx (numba.tests.test_withlifting.TestLiftObj.test_case16_scipy_call_in_objmode_ctx) ... skipped 'SciPy needed for test'
test_case17_print_own_bytecode (numba.tests.test_withlifting.TestLiftObj.test_case17_print_own_bytecode) ... ok
test_case18_njitfunc_passed_to_objmode_ctx (numba.tests.test_withlifting.TestLiftObj.test_case18_njitfunc_passed_to_objmode_ctx) ... ok
test_case19_recursion (numba.tests.test_withlifting.TestLiftObj.test_case19_recursion) ... ERROR
test_case20_rng_works_ok (numba.tests.test_withlifting.TestLiftObj.test_case20_rng_works_ok) ... expected failure
test_case21_rng_seed_works_ok (numba.tests.test_withlifting.TestLiftObj.test_case21_rng_seed_works_ok) ... ok
test_example01 (numba.tests.test_withlifting.TestLiftObj.test_example01) ... ok
test_lift_objmode_array_in (numba.tests.test_withlifting.TestLiftObj.test_lift_objmode_array_in) ... ok
test_lift_objmode_basic (numba.tests.test_withlifting.TestLiftObj.test_lift_objmode_basic) ... ok
test_lift_objmode_define_new_unused (numba.tests.test_withlifting.TestLiftObj.test_lift_objmode_define_new_unused) ... ok
test_lift_objmode_return_array (numba.tests.test_withlifting.TestLiftObj.test_lift_objmode_return_array) ... ok
test_lift_objmode_return_simple (numba.tests.test_withlifting.TestLiftObj.test_lift_objmode_return_simple) ... ok
test_lift_objmode_using_list (numba.tests.test_withlifting.TestLiftObj.test_lift_objmode_using_list) ... ERROR
test_lift_objmode_var_redef (numba.tests.test_withlifting.TestLiftObj.test_lift_objmode_var_redef) ... ok
test_objmode_closure_type_in_overload (numba.tests.test_withlifting.TestLiftObj.test_objmode_closure_type_in_overload) ... ok
test_objmode_closure_type_in_overload_error (numba.tests.test_withlifting.TestLiftObj.test_objmode_closure_type_in_overload_error) ... ok
test_objmode_gv_mod_attr (numba.tests.test_withlifting.TestLiftObj.test_objmode_gv_mod_attr) ... ok
test_objmode_gv_mod_attr_error (numba.tests.test_withlifting.TestLiftObj.test_objmode_gv_mod_attr_error) ... ok
test_objmode_gv_mod_attr_error_multiple (numba.tests.test_withlifting.TestLiftObj.test_objmode_gv_mod_attr_error_multiple) ... ok
test_objmode_gv_variable (numba.tests.test_withlifting.TestLiftObj.test_objmode_gv_variable) ... ok
test_objmode_gv_variable_error (numba.tests.test_withlifting.TestLiftObj.test_objmode_gv_variable_error) ... ok
test_objmode_in_overload (numba.tests.test_withlifting.TestLiftObj.test_objmode_in_overload) ... ok
test_objmode_invalid_use (numba.tests.test_withlifting.TestLiftObj.test_objmode_invalid_use) ... ok
test_objmode_jitclass (numba.tests.test_withlifting.TestLiftObj.test_objmode_jitclass) ... ok
test_objmode_multi_type_args (numba.tests.test_withlifting.TestLiftObj.test_objmode_multi_type_args) ... ok
test_objmode_reflected_list (numba.tests.test_withlifting.TestLiftObj.test_objmode_reflected_list) ... ok
test_objmode_reflected_set (numba.tests.test_withlifting.TestLiftObj.test_objmode_reflected_set) ... ok
test_objmode_typed_dict (numba.tests.test_withlifting.TestLiftObj.test_objmode_typed_dict) ... ok
test_objmode_typed_list (numba.tests.test_withlifting.TestLiftObj.test_objmode_typed_list) ... ok
test_objmode_use_of_view (numba.tests.test_withlifting.TestLiftObj.test_objmode_use_of_view) ... ok

======================================================================
ERROR: test_case06_double_objmode (numba.tests.test_withlifting.TestLiftObj.test_case06_double_objmode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/tests/test_withlifting.py", line 549, in test_case06_double_objmode
    njit(foo)(123)
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/dispatcher.py", line 471, in _compile_for_args
    error_rewrite(e, 'unsupported_error')
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/dispatcher.py", line 407, in error_rewrite
    raise e
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/dispatcher.py", line 420, in _compile_for_args
    return_val = self.compile(tuple(argtypes))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/dispatcher.py", line 965, in compile
    cres = self._compiler.compile(args, return_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/dispatcher.py", line 125, in compile
    status, retval = self._compile_cached(args, return_type)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/dispatcher.py", line 139, in _compile_cached
    retval = self._compile_core(args, return_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/dispatcher.py", line 152, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/compiler.py", line 770, in compile_extra
    return pipeline.compile_extra(func)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/compiler.py", line 461, in compile_extra
    return self._compile_bytecode()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/compiler.py", line 529, in _compile_bytecode
    return self._compile_core()
           ^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/compiler.py", line 508, in _compile_core
    raise e
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/compiler.py", line 495, in _compile_core
    pm.run(self.state)
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/compiler_machinery.py", line 368, in run
    raise patched_exception
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/compiler_machinery.py", line 356, in run
    self._runPass(idx, pass_inst, state)
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/compiler_machinery.py", line 311, in _runPass
    mutated |= check(pss.run_pass, internal_state)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/compiler_machinery.py", line 273, in check
    mangled = func(compiler_state)
              ^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/untyped_passes.py", line 278, in run_pass
    cres = compile_ir(state.typingctx, state.targetctx, main,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/compiler.py", line 833, in compile_ir
    return pipeline.compile_ir(func_ir=func_ir, lifted=lifted,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/compiler.py", line 471, in compile_ir
    return self._compile_ir()
           ^^^^^^^^^^^^^^^^^^
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/compiler.py", line 536, in _compile_ir
    return self._compile_core()
           ^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/compiler.py", line 508, in _compile_core
    raise e
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/compiler.py", line 495, in _compile_core
    pm.run(self.state)
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/compiler_machinery.py", line 368, in run
    raise patched_exception
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/compiler_machinery.py", line 356, in run
    self._runPass(idx, pass_inst, state)
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/compiler_machinery.py", line 311, in _runPass
    mutated |= check(pss.run_pass, internal_state)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/compiler_machinery.py", line 273, in check
    mangled = func(compiler_state)
              ^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/typed_passes.py", line 110, in run_pass
    typemap, return_type, calltypes, errs = type_inference_stage(
                                            ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/typed_passes.py", line 89, in type_inference_stage
    infer.build_constraint()
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/typeinfer.py", line 1039, in build_constraint
    self.constrain_statement(inst)
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/typeinfer.py", line 1413, in constrain_statement
    raise UnsupportedError(msg, loc=inst.loc)
numba.core.errors.UnsupportedError: Failed in nopython mode pipeline (step: Handle with contexts)
Failed in nopython mode pipeline (step: nopython frontend)
Unsupported constraint encountered: enter_with $phi22.0

File "numba/tests/test_withlifting.py", line 542:
        def foo(x):
            <source elided>
            # pattern useful?
            with objmode_context():
            ^


======================================================================
ERROR: test_case19_recursion (numba.tests.test_withlifting.TestLiftObj.test_case19_recursion)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/tests/test_withlifting.py", line 747, in test_case19_recursion
    cfoo(np.array([1, 2, 3]))
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

======================================================================
ERROR: test_lift_objmode_using_list (numba.tests.test_withlifting.TestLiftObj.test_lift_objmode_using_list)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/ir.py", line 271, in get
    return self._con[name]
           ~~~~~~~~~^^^^^^
KeyError: 'i'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/ir.py", line 1178, in get_exact
    return self.localvars.get(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/ir.py", line 273, in get
    raise NotDefinedError(name)
numba.core.errors.NotDefinedError: The compiler failed to analyze the bytecode. Variable 'i' is not defined.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/ir.py", line 271, in get
    return self._con[name]
           ~~~~~~~~~^^^^^^
KeyError: 'i'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/interpreter.py", line 1783, in _dispatch
    return fn(inst, **kws)
           ^^^^^^^^^^^^^^^
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/interpreter.py", line 2148, in op_LOAD_FAST
    self.store(value=self.get(srcname), name=res)
                     ^^^^^^^^^^^^^^^^^
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/interpreter.py", line 1829, in get
    var = self.current_scope.get(name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/ir.py", line 1170, in get
    return self.get_exact(name)
           ^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/ir.py", line 1181, in get_exact
    return self.parent.get(name)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/ir.py", line 1170, in get
    return self.get_exact(name)
           ^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/ir.py", line 1178, in get_exact
    return self.localvars.get(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/ir.py", line 273, in get
    raise NotDefinedError(name)
numba.core.errors.NotDefinedError: The compiler failed to analyze the bytecode. Variable 'i' is not defined.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/tests/test_withlifting.py", line 301, in core
    fn(self, *args, **kwargs)
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/tests/test_withlifting.py", line 436, in test_lift_objmode_using_list
    self.assert_equal_return_and_stdout(foo, arg)
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/tests/test_withlifting.py", line 334, in assert_equal_return_and_stdout
    cfunc.compile(tuple(map(typeof, c_args)))
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/dispatcher.py", line 965, in compile
    cres = self._compiler.compile(args, return_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/dispatcher.py", line 125, in compile
    status, retval = self._compile_cached(args, return_type)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/dispatcher.py", line 139, in _compile_cached
    retval = self._compile_core(args, return_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/dispatcher.py", line 152, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/compiler.py", line 770, in compile_extra
    return pipeline.compile_extra(func)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/compiler.py", line 461, in compile_extra
    return self._compile_bytecode()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/compiler.py", line 529, in _compile_bytecode
    return self._compile_core()
           ^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/compiler.py", line 508, in _compile_core
    raise e
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/compiler.py", line 495, in _compile_core
    pm.run(self.state)
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/compiler_machinery.py", line 368, in run
    raise patched_exception
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/compiler_machinery.py", line 356, in run
    self._runPass(idx, pass_inst, state)
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/compiler_machinery.py", line 311, in _runPass
    mutated |= check(pss.run_pass, internal_state)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/compiler_machinery.py", line 273, in check
    mangled = func(compiler_state)
              ^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/untyped_passes.py", line 86, in run_pass
    func_ir = interp.interpret(bc)
              ^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/interpreter.py", line 1379, in interpret
    self._dispatch(inst, kws)
  File "/mnt/home/sklam/dev/numba-py312-workspace/numba/numba/core/interpreter.py", line 1794, in _dispatch
    raise err
numba.core.errors.NotDefinedError: Failed in nopython mode pipeline (step: analyzing bytecode)
The compiler failed to analyze the bytecode. Variable 'i' is not defined.

File "numba/tests/test_withlifting.py", line 432:
        def foo(x):
            <source elided>
                y = [1, 2, 3] + x
                y = np.asarray([1 / i for i in y])
                ^


----------------------------------------------------------------------
Ran 45 tests in 12.164s

FAILED (errors=3, skipped=1, expected failures=2)
